// Set of "City" locations that get the CityIcon and #9F9FEE background
// Format: "City, State"
export const CITY_LOCATIONS_LIST = [
	'The Bronx, New York',
	'Brooklyn, New York',
	'Manhattan, New York',
	'Queens, New York',
	'Staten Island, New York',
	'New York, New York',
	'Los Angeles, California',
	'Chicago, Illinois',
	'Houston, Texas',
	'Phoenix, Arizona',
	'Philadelphia, Pennsylvania',
	'San Antonio, Texas',
	'San Diego, California',
	'Dallas, Texas',
	'Jacksonville, Florida',
	'Austin, Texas',
	'Fort Worth, Texas',
	'San Jose, California',
	'Columbus, Ohio',
	'Charlotte, North Carolina',
	'Indianapolis, Indiana',
	'San Francisco, California',
	'Seattle, Washington',
	'Denver, Colorado',
	'Oklahoma City, Oklahoma',
	'Nashville, Tennessee',
	'El Paso, Texas',
	'Washington, District of Columbia',
	'Las Vegas, Nevada',
	'Boston, Massachusetts',
	'Portland, Oregon',
	'Louisville, Kentucky',
	'Memphis, Tennessee',
	'Detroit, Michigan',
	'Baltimore, Maryland',
	'Milwaukee, Wisconsin',
	'Albuquerque, New Mexico',
	'Tucson, Arizona',
	'Fresno, California',
	'Sacramento, California',
	'Mesa, Arizona',
	'Kansas City, Missouri',
	'Atlanta, Georgia',
	'Colorado Springs, Colorado',
	'Omaha, Nebraska',
	'Raleigh, North Carolina',
	'Virginia Beach, Virginia',
	'Long Beach, California',
	'Miami, Florida',
	'Oakland, California',
	'Minneapolis, Minnesota',
	'Tulsa, Oklahoma',
	'Bakersfield, California',
	'Wichita, Kansas',
	'Arlington, Texas',
	'Aurora, Colorado',
	'Tampa, Florida',
	'New Orleans, Louisiana',
	'Cleveland, Ohio',
	'Honolulu, Hawaii',
	'Anaheim, California',
	'Lexington, Kentucky',
	'Stockton, California',
	'Corpus Christi, Texas',
	'Henderson, Nevada',
	'Riverside, California',
	'Newark, New Jersey',
	'Saint Paul, Minnesota',
	'Santa Ana, California',
	'Cincinnati, Ohio',
	'Irvine, California',
	'Orlando, Florida',
	'Pittsburgh, Pennsylvania',
	'St. Louis, Missouri',
	'Greensboro, North Carolina',
	'Jersey City, New Jersey',
	'Anchorage, Alaska',
	'Lincoln, Nebraska',
	'Plano, Texas',
	'Durham, North Carolina',
	'Buffalo, New York',
	'Chandler, Arizona',
	'Chula Vista, California',
	'Toledo, Ohio',
	'Madison, Wisconsin',
	'Gilbert, Arizona',
	'Reno, Nevada',
	'Fort Wayne, Indiana',
	'North Las Vegas, Nevada',
	'St. Petersburg, Florida',
	'Lubbock, Texas',
	'Irving, Texas',
	'Laredo, Texas',
	'Winston-Salem, North Carolina',
	'Chesapeake, Virginia',
	'Glendale, Arizona',
	'Garland, Texas',
	'Scottsdale, Arizona',
	'Norfolk, Virginia',
	'Boise, Idaho',
	'Fremont, California',
	'Spokane, Washington',
	'Santa Clarita, California',
	'Baton Rouge, Louisiana',
	'Richmond, Virginia',
	'Hialeah, Florida',
	'San Bernardino, California',
	'Tacoma, Washington',
	'Modesto, California',
	'Huntsville, Alabama',
	'Des Moines, Iowa',
	'Yonkers, New York',
	'Rochester, New York',
	'Morena Valley, California',
	'Fayetteville, North Carolina',
	'Fontana, California',
	'Columbus, Georgia',
	'Worcester, Massachusetts',
	'Port St. Lucie, Florida',
	'Little Rock, Arkansas',
	'Augusta, Georgia',
	'Oxnard, California',
	'Birmingham, Alabama',
	'Montgomery, Alabama',
	'Frisco, Texas',
	'Amarillo, Texas',
	'Salt Lake City, Utah',
	'Grand Rapids, Michigan',
	'Huntington Beach, California',
	'Overland Park, Kansas',
	'Glendale, California',
	'Tallahassee, Florida',
	'Grand Prairie, Texas',
	'McKinney, Texas',
	'Cape Coral, Florida',
	'Sioux Falls, South Dakota',
	'Peoria, Arizona',
	'Providence, Rhode Island',
	'Vancouver, Washington',
	'Knoxville, Tennessee',
	'Akron, Ohio',
	'Shreveport, Louisiana',
	'Mobile, Alabama',
	'Brownsville, Texas',
	'Newport News, Virginia',
	'Fort Lauderdale, Florida',
	'Chattanooga, Tennessee',
	'Tempe, Arizona',
	'Santa Rosa, California',
	'Eugene, Oregon',
	'Elk Grove, California',
	'Salem, Oregon',
	'Ontario, California',
	'Cary, North Carolina',
	'Rancho Cucamonga, California',
	'Oceanside, California',
	'Lancaster, California',
	'Garden Grove, California',
	'Pembroke Pines, Florida',
	'Fort Collins, Colorado',
	'Palmdale, California',
	'Springfield, Missouri',
	'Clarksville, Tennessee',
	'Salinas, California',
	'Hayward, California',
	'Paterson, New Jersey',
	'Alexandria, Virginia',
	'Macon, Georgia',
	'Corona, California',
	'Kansas City, Kansas',
	'Lakewood, Colorado',
	'Springfield, Massachusetts',
	'Sunnyvale, California',
	'Jackson, Mississippi',
	'Killeen, Texas',
	'Hollywood, Florida',
	'Murfreesboro, Tennessee',
	'Pasadena, Texas',
	'Bellevue, Washington',
	'Pomona, California',
	'Escondido, California',
	'Joliet, Illinois',
	'Charleston, South Carolina',
	'Mesquite, Texas',
	'Naperville, Illinois',
	'Rockford, Illinois',
	'Bridgeport, Connecticut',
	'Syracuse, New York',
	'Savannah, Georgia',
	'Roseville, California',
	'Torrance, California',
	'Fullerton, California',
	'Surprise, Arizona',
	'McAllen, Texas',
	'Thornton, Colorado',
	'Visalia, California',
	'Olathe, Kansas',
	'Gainesville, Florida',
	'West Valley City, Utah',
	'Orange, California',
	'Denton, Texas',
	'Warren, Michigan',
	'Pasadena, California',
	'Waco, Texas',
	'Cedar Rapids, Iowa',
	'Daytona Beach, Florida',
	'Elizabeth, New Jersey',
	'Hampton, Virginia',
	'Columbia, South Carolina',
	'Kent, Washington',
	'Stamford, Connecticut',
	'Lakewood, New Jersey',
	'Victorville, California',
	'Miramar, Florida',
	'Coral Springs, Florida',
	'Sterling Heights, Michigan',
	'New Haven, Connecticut',
	'Carrollton, Texas',
	'Midland, Texas',
	'Norman, Oklahoma',
	'Santa Clara, California',
	'Athens, Georgia',
	'Thousand Oaks, California',
	'Topeka, Kansas',
	'Simi Valley, California',
	'Columbia, Missouri',
	'Vallejo, California',
	'Fargo, North Dakota',
	'Allentown, Pennsylvania',
	'Pearland, Texas',
	'Concord, California',
	'Abilene, Texas',
	'Arvada, Colorado',
	'Berkeley, California',
	'Ann Arbor, Michigan',
	'Independence, Missouri',
	'Rochester, Minnesota',
	'Lafayette, Louisiana',
	'Hartford, Connecticut',
	'College Station, Texas',
	'Clovis, California',
	'Fairfield, California',
	'Palm Bay, Florida',
	'Costa Mesa, California',
	'Wilmington, North Carolina',
	'Lakeland, Florida',
	'Billings, Montana',
	'High Point, North Carolina',
	'Round Rock, Texas',
	'Cambridge, Massachusetts',
	'Richardson, Texas',
	'Redondo Beach, California',
	'Clearwater, Florida',
	'Pueblo, Colorado',
	'West Jordan, Utah',
	'Evansville, Indiana',
	'League City, Texas',
	'Downey, California',
	'Richmond, California',
	'Westminster, Colorado',
	'Manchester, New Hampshire',
	'Lowel, Massachusetts',
	'Wilmington, Delaware',
	'Antioch, California',
	'Beaumont, Texas',
	'Provo, Utah',
	'Springfield, Illinois',
	'Elgin, Illinois',
	'Odessa, Texas',
	'Waterbury, Connecticut',
	'Dorchester, Massachusetts',
	'Lansing, Michigan',
	'Everett, Washington',
	'Pompano Beach, Florida',
	'Carlsbad, California',
	'West Covina, California',
	'Lewisville, Texas',
	'Gresham, Oregon',
	'Daly City, California',
	'Tyler, Texas',
	'Murrieta, California',
	'Green Bay, Wisconsin',
	'Ventura, California',
	'Centennial, Colorado',
	'West Palm Beach, Florida',
	'Boulder, Colorado',
	'North Charleston, South Carolina',
	'Sparks, Nevada',
	'South Bend, Indiana',
	'El Monte, California',
	'Inglewood, California',
	'Edison, New Jersey',
	'Davenport, Iowa',
	'Hillsboro, Oregon',
	'Woodbridge, New Jersey',
	'Jurupa Valley, California',
	'Renton, Washington',
	'Rialto, California',
	'Allen, Texas',
	'Sandy Springs, Georgia',
	'Burbank, California',
	'San Mateo, California',
	'Brockton, Massachusetts',
	'El Cajon, California',
	'Vacaville, California',
	'Clinton, Michigan',
	'Roanoke,Virginia',
	'Beaverton, Oregon',
	'Spokane Valley, Washington',
	"Lee's Summit, Missouri",
	'Rio Rancho, New Mexico',
	'Edinburg, Texas',
	'Bend, Oregon',
	'Hesperia, California',
	'South Gate, California',
	'Vista, California',
	'Tuscaloosa, Alabama',
	'Mission Viejo, California',
	'Nampa, Idaho',
	'Greeley, Colorado',
	'Davie, Florida',
	'San Angelo, Texas',
	'Kenosha, Wisconsin',
	'Alhambra, California',
	'Concord, North Carolina',
	'Menifee, California',
	'New Bedford, Massachusetts',
	'Franklin, Tennessee',
	'South Fulton, Georgia',
	'Orem, Utah',
	'Putnam, Connecticut',
];

export const CITY_LOCATIONS_SET = new Set(
	CITY_LOCATIONS_LIST.map((s) => s.toLowerCase())
);
