import { Contact } from '@/constants/types';

export const extraContacts: Contact[] = [
	{
		name: 'Alex Rivera',
		email: 'arivera@musicstudios.com',
		category: 'music',
		company: 'Harmonic Waves Studios',
	},
	{
		name: 'Sarah Johnson',
		email: 'sjohnson@lawfirm.com',
		category: 'lawyer',
		company: 'Johnson & Associates',
	},
	{
		name: 'Michael Chen',
		email: 'mchen@medcenter.org',
		category: 'doctor',
		company: 'City Medical Center',
	},
	{
		name: 'Emma Rodriguez',
		email: 'erodriguez@bizventures.com',
		category: 'business',
		company: 'Rodriguez Enterprises',
	},
	{
		name: 'James Wilson',
		email: 'jwilson@grandhotel.com',
		category: 'hospitality',
		company: 'Grand Hotel Group',
	},
	{
		name: 'Patricia Taylor',
		email: 'ptaylor@financepros.com',
		category: 'finance',
		company: 'Taylor Financial Advisors',
	},
	{
		name: 'Robert Miller',
		email: 'rmiller@education.org',
		category: 'teacher',
		company: 'Westside High School',
	},
	{
		name: 'Linda Garcia',
		email: 'lgarcia@engineersllc.com',
		category: 'engineer',
		company: 'Innovative Engineering Solutions',
	},
	{
		name: 'David Lee',
		email: 'dlee@architecturedesign.com',
		category: 'architect',
		company: 'Lee Design Associates',
	},
	{
		name: 'Elizabeth Brown',
		email: 'ebrown@accountingfirm.com',
		category: 'accountant',
		company: 'Brown & Co. Accounting',
	},
	{
		name: 'Thomas Martinez',
		email: 'tmartinez@dentalcare.com',
		category: 'dentist',
		company: 'Bright Smile Dental',
	},
	{
		name: 'Jennifer Anderson',
		email: 'janderson@hospital.org',
		category: 'nurse',
		company: 'Regional Hospital',
	},
	{
		name: 'William White',
		email: 'wwhite@pharmacy.com',
		category: 'pharmacist',
		company: "White's Pharmacy",
	},
	{
		name: 'Margaret Harris',
		email: 'mharris@animalhospital.org',
		category: 'veterinarian',
		company: 'Happy Paws Animal Hospital',
	},
	{
		name: 'Richard Clark',
		email: 'rclark@psychology.org',
		category: 'psychologist',
		company: 'Clark Psychology Practice',
	},
	{
		name: 'Susan Lewis',
		email: 'slewis@newsagency.com',
		category: 'journalist',
		company: 'Daily Tribune',
	},
	{
		name: 'Joseph Walker',
		email: 'jwalker@culinary.com',
		category: 'chef',
		company: "Walker's Fine Dining",
	},
	{
		name: 'Dorothy Young',
		email: 'dyoung@realty.com',
		category: 'realtor',
		company: 'Young Real Estate',
	},
	{
		name: 'Charles King',
		email: 'cking@techsolutions.com',
		category: 'developer',
		company: 'King Software Solutions',
	},
	{
		name: 'Carol Scott',
		email: 'cscott@designstudio.com',
		category: 'designer',
		company: 'Creative Designs Studio',
	},
	{
		name: 'Daniel Green',
		email: 'dgreen@consulting.com',
		category: 'consultant',
		company: 'Green Business Consulting',
	},
	{
		name: 'Ruth Baker',
		email: 'rbaker@photography.com',
		category: 'photographer',
		company: 'Baker Photography',
	},
	{
		name: 'Steven Nelson',
		email: 'snelson@electricservices.com',
		category: 'electrician',
		company: 'Nelson Electrical Services',
	},
	{
		name: 'Donna Carter',
		email: 'dcarter@plumbing.com',
		category: 'plumber',
		company: 'Carter Plumbing Solutions',
	},
	{
		name: 'Kenneth Adams',
		email: 'kadams@autorepair.com',
		category: 'mechanic',
		company: 'Adams Auto Repair',
	},
	{
		name: 'Michelle Turner',
		email: 'mturner@researchlab.org',
		category: 'scientist',
		company: 'Turner Research Institute',
	},
	{
		name: 'Edward Mitchell',
		email: 'emitchell@aviation.com',
		category: 'pilot',
		company: 'Mitchell Aviation',
	},
	{
		name: 'Lisa Perez',
		email: 'lperez@visionclinic.com',
		category: 'optometrist',
		company: 'Clear Vision Clinic',
	},
	{
		name: 'George Phillips',
		email: 'gphillips@therapy.org',
		category: 'therapist',
		company: 'Phillips Therapy Center',
	},
	{
		name: 'Sandra Evans',
		email: 'sevans@surgicalcenter.org',
		category: 'surgeon',
		company: 'Evans Surgical Associates',
	},
	{
		name: 'Ronald Torres',
		email: 'rtorres@policedept.gov',
		category: 'police',
		company: 'City Police Department',
	},
	{
		name: 'Shirley Nguyen',
		email: 'snguyen@firedept.gov',
		category: 'firefighter',
		company: 'City Fire Department',
	},
	{
		name: 'Kevin Moore',
		email: 'kmoore@emergencyservices.org',
		category: 'paramedic',
		company: 'Moore Emergency Services',
	},
	{
		name: 'Deborah Jackson',
		email: 'djackson@university.edu',
		category: 'professor',
		company: 'State University',
	},
	{
		name: 'Brian Martin',
		email: 'bmartin@marketingfirm.com',
		category: 'marketer',
		company: 'Martin Marketing Solutions',
	},
];
