import { Contact } from '@/constants/types';

export const lawyerContacts: Contact[] = [
	{
		name: 'John Doe',
		email: 'johndoe@email.com',
		category: 'lawyer',
		company: 'Doe & Associates',
	},
	{
		name: 'Sarah Johnson',
		email: 'sjohnson@legalfirm.com',
		category: 'lawyer',
		company: 'Johnson Legal Group',
	},
	{
		name: 'Michael Rodriguez',
		email: 'mrodriguez@lawoffices.com',
		category: 'lawyer',
		company: 'Rodriguez Law Offices',
	},
	{
		name: 'Emily Chen',
		email: 'echen@legalpractice.com',
		category: 'lawyer',
		company: 'Chen & Partners',
	},
	{
		name: 'Robert Williams',
		email: 'rwilliams@attorneygroup.com',
		category: 'lawyer',
		company: 'Williams Attorney Group',
	},
	{
		name: 'Jessica Martinez',
		email: 'jmartinez@legalcounsel.com',
		category: 'lawyer',
		company: 'Martinez Legal Counsel',
	},
	{
		name: 'David Thompson',
		email: 'dthompson@lawpartners.com',
		category: 'lawyer',
		company: 'Thompson Law Partners',
	},
	{
		name: 'Lisa Brown',
		email: 'lbrown@legaladvocates.com',
		category: 'lawyer',
		company: 'Brown Legal Advocates',
	},
	{
		name: 'Kevin Anderson',
		email: 'kanderson@justicelegal.com',
		category: 'lawyer',
		company: 'Justice Legal Services',
	},
	{
		name: 'Amanda Taylor',
		email: 'ataylor@litigationlaw.com',
		category: 'lawyer',
		company: 'Taylor Litigation Specialists',
	},
	{
		name: 'Thomas Wilson',
		email: 'twilson@lawassociates.com',
		category: 'lawyer',
		company: 'Wilson Law Associates',
	},
	{
		name: 'Stephanie Garcia',
		email: 'sgarcia@counselgroup.com',
		category: 'lawyer',
		company: 'Garcia Counsel Group',
	},
	{
		name: 'Andrew Miller',
		email: 'amiller@legalexperts.com',
		category: 'lawyer',
		company: 'Miller Legal Experts',
	},
	{
		name: 'Jennifer Lee',
		email: 'jlee@justiceattorneys.com',
		category: 'lawyer',
		company: 'Lee Justice Attorneys',
	},
	{
		name: 'Christopher Jackson',
		email: 'cjackson@legalteam.com',
		category: 'lawyer',
		company: 'Jackson Legal Team',
	},
	{
		name: 'Nicole White',
		email: 'nwhite@lawgroup.com',
		category: 'lawyer',
		company: 'White Law Group',
	},
	{
		name: 'Daniel Patel',
		email: 'dpatel@attorneys.com',
		category: 'lawyer',
		company: 'Patel Attorneys LLC',
	},
	{
		name: 'Rachel Robinson',
		email: 'rrobinson@legalconsultants.com',
		category: 'lawyer',
		company: 'Robinson Legal Consultants',
	},
	{
		name: 'Brian Davis',
		email: 'bdavis@lawpractice.com',
		category: 'lawyer',
		company: 'Davis Law Practice',
	},
	{
		name: 'Michelle Nguyen',
		email: 'mnguyen@legalcounselors.com',
		category: 'lawyer',
		company: 'Nguyen Legal Counselors',
	},
	{
		name: 'Patrick Kim',
		email: 'pkim@lawindividuals.com',
		category: 'lawyer',
		company: 'Kim & Associates',
	},
];
