export const SELECTED_CONTACT_MARKER_VIEWBOX_WIDTH = 78;
export const SELECTED_CONTACT_MARKER_VIEWBOX_HEIGHT = 75;
export const SELECTED_CONTACT_MARKER_CENTER_X = 39.5;
export const SELECTED_CONTACT_MARKER_CENTER_Y = 43.5;
export const SELECTED_CONTACT_MARKER_CENTER_OUTER_DIAMETER = 31;
